/**
 * Engine api
 * Engine APIs
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Attire of person predicted by the engine during peopleDetailEvent event
 */
export type Color = 'Black' | 'Blue' | 'Cyan' | 'Gray' | 'Green' | 'Purple' | 'Red' | 'Yellow' | 'Silver' | 'Gold' | 'White' | 'Undetermined';

export const Color = {
    Black: 'Black' as Color,
    Blue: 'Blue' as Color,
    Cyan: 'Cyan' as Color,
    Gray: 'Gray' as Color,
    Green: 'Green' as Color,
    Purple: 'Purple' as Color,
    Red: 'Red' as Color,
    Yellow: 'Yellow' as Color,
    Silver: 'Silver' as Color,
    Gold: 'Gold' as Color,
    White: 'White' as Color,
    Undetermined: 'Undetermined' as Color
};