/**
 * Engine api
 * Engine APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { FaceEventEventDetails } from './faceEventEventDetails';


export interface Event {
    readonly _id?: string;
    eventDetails?: FaceEventEventDetails;
    eventSnaps?: Array<string>;
    eventClips?: Array<string>;
    readonly updated?: Date;
    readonly created?: Date;
    etag?: string;
}