/**
 * Engine api
 * Engine APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FaceEventEventDetails { 
    /**
     * _id of camera #$ref: '#/components/schemas/camera' from project cameras
     */
    cameraId?: string;
    startTimeStamp?: number;
    endTimeStamp?: number;
}