/**
 * Engine api
 * Engine APIs
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { Color } from './color';
import { VehicleClass } from './vehicleClass';


export interface MetaAnprEvent { 
    /**
     * Vehicle number detected in OCR
     */
    vehicleNumber?: string;
    vehicleClass?: VehicleClass;
    vehicleColor?: Color;
}