/**
 * Engine api
 * Engine APIs
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Vehicle classifications are as follows:  * `'TwoWheeler'` - Two Wheeler vehicles i.e. Motor Cycle, Bike  * `'ThreeWheeler'` - Three Wheeler vehicles i.e. Auto Rickshaw  * `'FourWheeler'` - Four Wheeler vehicles i.e. Car, SUV  * `'HeavyVehicle'` - Heavy Vehicles i.e. Bus, Truck   
 */
export type VehicleClass = 'TwoWheeler' | 'ThreeWheeler' | 'FourWheeler' | 'HeavyVehicle';

export const VehicleClass = {
    TwoWheeler: 'TwoWheeler' as VehicleClass,
    ThreeWheeler: 'ThreeWheeler' as VehicleClass,
    FourWheeler: 'FourWheeler' as VehicleClass,
    HeavyVehicle: 'HeavyVehicle' as VehicleClass
};